-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.users
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    email character varying(50) NOT NULL UNIQUE,
    password character varying(20) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_seekers
(
    id integer NOT NULL,
    national_id character varying(11) NOT NULL UNIQUE,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    date_of_birth date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employers
(
    id integer NOT NULL,
    company_name character varying(75) NOT NULL,
    web_address character varying(75) NOT NULL,
    phone_number character varying(15) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employee
(
    id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    "position" integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.activation_codes
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    code character varying(125) NOT NULL,
    is_used boolean NOT NULL,
    confirm_date date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.activation_employers
(
    id integer NOT NULL,
    emloyer_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.activation_job_seekers
(
    id integer NOT NULL,
    job_seeker_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.activation_employers_by_employee
(
    id integer NOT NULL,
    employer_id integer NOT NULL,
    employee_id integer NOT NULL,
    confirmed_date date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_positions
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    "position" character varying(50) NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

ALTER TABLE public.users
    ADD FOREIGN KEY (id)
    REFERENCES public.job_seekers (id)
    NOT VALID;


ALTER TABLE public.users
    ADD FOREIGN KEY (id)
    REFERENCES public.employers (id)
    NOT VALID;


ALTER TABLE public.users
    ADD FOREIGN KEY (id)
    REFERENCES public.employee (id)
    NOT VALID;


ALTER TABLE public.activation_codes
    ADD FOREIGN KEY (id)
    REFERENCES public.activation_employers (id)
    NOT VALID;


ALTER TABLE public.activation_codes
    ADD FOREIGN KEY (id)
    REFERENCES public.activation_job_seekers (id)
    NOT VALID;


ALTER TABLE public.employee
    ADD FOREIGN KEY ("position")
    REFERENCES public.job_positions (id)
    NOT VALID;


ALTER TABLE public.activation_job_seekers
    ADD FOREIGN KEY (job_seeker_id)
    REFERENCES public.job_seekers (id)
    NOT VALID;


ALTER TABLE public.activation_employers
    ADD FOREIGN KEY (emloyer_id)
    REFERENCES public.employee (id)
    NOT VALID;


ALTER TABLE public.activation_employers_by_employee
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (id)
    NOT VALID;


ALTER TABLE public.activation_employers_by_employee
    ADD FOREIGN KEY (employee_id)
    REFERENCES public.employee (id)
    NOT VALID;

END;